stages:

- stage: terraform
  displayName: terraform infra
  jobs:

  - job: terraformapply
    displayName: terraform apply and init

    steps:
    - checkout: self

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    # 1. Terraform Init
    - task: TerraformTask@5
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: 'terraform'
        backendServiceArm: 'hdfcauto'
        backendAzureRmResourceGroupName: 'credRg'
        backendAzureRmStorageAccountName: 'credpayprojectjaya'
        backendAzureRmContainerName: 'statefile'
        backendAzureRmKey: 'credpay.teraform.tfstate'

    # 2. Terraform Plan
    - task: TerraformTask@5
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: 'terraform'
        environmentServiceNameAzureRM: 'hdfcauto'
    - task: TerraformTask@5
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: 'terraform'
        environmentServiceNameAzureRM: 'hdfcauto'
    - task: TerraformTask@5
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        workingDirectory: 'terraform'
        environmentServiceNameAzureRM: 'hdfcauto'


