#pipeline code

pool:
  vmImage: ubuntu-latest

variables:
  acrServiceConnection: 'acrserviceconnection'
  frontendRepository: 'credpay/frontend'
  userRepository: 'credpay/user-service'
  paymentRepository: 'credpay/payment-service'
  tag: '$(Build.BuildId)'

stages:

- stage: terraform
  displayName: terraform infra
  jobs:

  - job: terraformapply
    displayName: terraform apply and init

    steps:
    - checkout: self
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: terraform
        backendServiceArm: 'hdfcauto'
        backendAzureRmOverrideSubscriptionID: 'e12f710f-4779-4738-bbb9-6b2e658c69f2'
        backendAzureRmResourceGroupName: 'credRg'
        backendAzureRmStorageAccountName: 'credpayprojectjaya'
        backendAzureRmContainerName: 'statefile'
        backendAzureRmKey: 'credpay.teraform.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: terraform
        backendServiceArm: 'hdfcauto'
        backendAzureRmOverrideSubscriptionID: 'e12f710f-4779-4738-bbb9-6b2e658c69f2'
        backendAzureRmResourceGroupName: 'credRg'
        backendAzureRmStorageAccountName: 'credpayprojectjaya'
        backendAzureRmContainerName: 'statefile'
        backendAzureRmKey: 'credpay.teraform.tfstate'

